include(CMakePackageConfigHelpers)
include(GNUInstallDirs)

set(OCS_INSTALL_TARGETS ocr_suite ocr_suite_viewer ocr_cli ocr_results_viewer)

install(
    TARGETS ${OCS_INSTALL_TARGETS}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}

    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)
