include(CMakePackageConfigHelpers)
include(GNUInstallDirs)

set(OCS_INSTALL_TARGETS ocr_suite ocr_suite_viewer)

install(
    TARGETS ${OCS_INSTALL_TARGETS}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}

    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    INCLUDES DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
)

# Don't include the tess_data - it's too big
# install(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/tessdata DESTINATION ${CMAKE_INSTALL_DATADIR}/tessdata)
